 (autoload 'js3-mode "js3" nil t)
   (add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(customize-set-variable 'js3-auto-indent-p t)
(customize-set-variable 'js3-boring-indentation t)
(customize-set-variable 'js3-enter-indents-newline t)
(customize-set-variable 'js3-highlight-level 3)
(customize-set-variable 'js3-include-gears-externs nil)
(customize-set-variable 'js3-include-rhino-externs nil)
(customize-set-variable 'js3-indent-tabs-mode t)
(customize-set-variable 'js3-mode-show-strict-warnings nil)
